# Generated by Django 5.1.2 on 2024-10-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_remove_brandcreation_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandcreation',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='brandcreation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='brandcreation',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='brandcreation',
            name='current_campaign',
        ),
        migrations.RemoveField(
            model_name='brandcreation',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='brandcreation',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='brandcreation',
            name='season',
        ),
    ]
