# Generated by Django 5.1.2 on 2024-10-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0005_rename_colors_brandcreation_benchmark_brands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcreation',
            name='competitor_brands',
            field=models.JSONField(null=True),
        ),
    ]
