# Generated by Django 5.1.2 on 2024-10-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0006_alter_brandcreation_competitor_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcreation',
            name='logo',
            field=models.CharField(max_length=500),
        ),
    ]
