# Generated by Django 5.1.2 on 2024-10-26 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0008_alter_color_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advanceddata',
            old_name='color_scheme',
            new_name='colorScheme',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='audience_interest',
            new_name='audienceInterest',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='benchmark_brands',
            new_name='benchmarkBrands',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='body_font',
            new_name='bodyFont',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='brand_guideline_docs',
            new_name='brandGuidelineDocs',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='competitor_brands',
            new_name='competitorBrands',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='copyright_text',
            new_name='copyrightText',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='cta_text',
            new_name='ctaText',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='current_campaign',
            new_name='currentCampaign',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='message_style',
            new_name='messageStyle',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='sub_title_font',
            new_name='subTitleFont',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='tag_line',
            new_name='tagLine',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='title_font',
            new_name='titleFont',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='tone_of_voice',
            new_name='toneOfVoice',
        ),
        migrations.RenameField(
            model_name='brandcreation',
            old_name='visual_style',
            new_name='visualStyle',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_code',
            new_name='colorCode',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_type',
            new_name='colorType',
        ),
        migrations.AddField(
            model_name='advanceddata',
            name='timePeriod',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandcreation',
            name='visualElements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='advanceddata',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advancedData', to='parameters.brandcreation'),
        ),
    ]
