# Generated by Django 5.1.2 on 2024-10-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0009_rename_color_scheme_advanceddata_colorscheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanceddata',
            name='timePeriod',
        ),
    ]
