# Generated by Django 5.1.2 on 2024-10-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0010_remove_advanceddata_timeperiod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='colorType',
            new_name='type',
        ),
    ]
