# Generated by Django 5.1.2 on 2024-10-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0011_rename_colortype_color_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvancedData',
            new_name='Advanced',
        ),
    ]
