# Generated by Django 5.1.2 on 2024-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0012_rename_advanceddata_advanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced',
            name='timePeriod',
            field=models.CharField(default=2024, max_length=50),
            preserve_default=False,
        ),
    ]
