# Generated by Django 5.1.2 on 2024-10-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0013_advanced_timeperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcreation',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
