# Generated by Django 5.1.2 on 2024-10-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0014_alter_brandcreation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcreation',
            name='productImage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='brandcreation',
            name='productPrompt',
            field=models.TextField(null=True),
        ),
    ]
